### ISSUE TITLE
Sort by Oldest to Newest

### ISSUE THREAD

**Issue by Droppisalt** [Delusoire/spicetify-extensions#3]
Same as https://github.com/Delusoire/spicetify-extensions/issues/1 but reversed. Would it also be possible to have an option to send to a playlist instead of playing immediately?

**Comment by Delusoire** [comment]
You can already do that by toggling on the *ascending* switch in your Spotify settings under the *Sort+* section. For ease of use, I have made it so that holding ctrl while clicking on the sort option inverts whatever sorting order you have set as default in 540a822.
There is a button on the top left that does just that, creates a playlist from the last sorted queue.

**Comment by Droppisalt** [comment]
Oh! Didn't notice your extension added these settings. Thanks!
